function errMode = idErrorMode(vTest, vTruth, vSubset)
%% errMode = tabulateErrorMode(vTest, vGT, vSubset)
%  returns membership of [TP TN FP FN] in vector vTest as graded by vGT
%  if optional vSubset logical vector is included, will use to restrict
%  errMode is a bit-encoded vector of size vTest where bits 0:3 correspond
%  to [TP TN FP FN];
if nargin < 3
    errMode = [ ...
        vTest==vTruth & vTruth>0 ...
        vTest==vTruth & ~vTruth ...
        vTest~=vTruth & ~vTruth ...
        vTest~=vTruth & vTruth>0 ...
        ];
else
    errMode = [ ...
        vTest==vTruth & vTruth>0 & vSubset>0 ...
        vTest==vTruth & ~vTruth & vSubset>0  ...
        vTest~=vTruth & ~vTruth & vSubset>0  ...
        vTest~=vTruth & vTruth>0 & vSubset>0 ...
        ];

return;
end
